apiVersion: v1
kind: Service
metadata:
  name: mern-app-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-port
  selector:
    app: mern-app-server
  type: LoadBalancer