apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-server
  name: mongo-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-server
  type: ClusterIP