apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mine
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer

# PV object commented out because dynamic provisioning is supported for PVC
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-pv
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce #ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: mine
#   mountOptions:
#     - debug

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mine
  accessModes:
    - ReadWriteOnce #ReadWriteMany
  resources:
    requests:
      storage: 2Gi